#! /usr/bin/sh

yes | brew install font-noto-color-emoji
yes | brew install font-noto-color-emoji-compat-test
yes | brew install font-noto-emoji
yes | brew install font-noto-kufi-arabic
yes | brew install font-noto-mono
yes | brew install font-noto-mono-for-powerline
yes | brew install font-noto-music
yes | brew install font-noto-naskh-arabic
yes | brew install font-noto-naskh-arabic-ui
yes | brew install font-noto-nastaliq-urdu
yes | brew install font-noto-nerd-font
yes | brew install font-noto-rashi-hebrew
yes | brew install font-noto-sans
yes | brew install font-noto-sans-adlam
yes | brew install font-noto-sans-adlam-unjoined
yes | brew install font-noto-sans-anatolian-hieroglyphs
yes | brew install font-noto-sans-arabic
yes | brew install font-noto-sans-arabic-ui
yes | brew install font-noto-sans-armenian
yes | brew install font-noto-sans-avestan
yes | brew install font-noto-sans-balinese
yes | brew install font-noto-sans-bamum
yes | brew install font-noto-sans-bassa-vah
yes | brew install font-noto-sans-batak
yes | brew install font-noto-sans-bengali
yes | brew install font-noto-sans-bengali-ui
yes | brew install font-noto-sans-bhaiksuki
yes | brew install font-noto-sans-brahmi
yes | brew install font-noto-sans-buginese
yes | brew install font-noto-sans-buhid
yes | brew install font-noto-sans-canadian-aboriginal
yes | brew install font-noto-sans-carian
yes | brew install font-noto-sans-caucasian-albanian
yes | brew install font-noto-sans-chakma
yes | brew install font-noto-sans-cham
yes | brew install font-noto-sans-cherokee
yes | brew install font-noto-sans-chorasmian
yes | brew install font-noto-sans-cjk
yes | brew install font-noto-sans-cjk-hk
yes | brew install font-noto-sans-cjk-jp
yes | brew install font-noto-sans-cjk-kr
yes | brew install font-noto-sans-cjk-sc
yes | brew install font-noto-sans-cjk-tc
yes | brew install font-noto-sans-coptic
yes | brew install font-noto-sans-cuneiform
yes | brew install font-noto-sans-cypriot
yes | brew install font-noto-sans-cypro-minoan
yes | brew install font-noto-sans-deseret
yes | brew install font-noto-sans-devanagari
yes | brew install font-noto-sans-devanagari-ui
yes | brew install font-noto-sans-display
yes | brew install font-noto-sans-duployan
yes | brew install font-noto-sans-egyptian-hieroglyphs
yes | brew install font-noto-sans-elbasan
yes | brew install font-noto-sans-elymaic
yes | brew install font-noto-sans-ethiopic
yes | brew install font-noto-sans-georgian
yes | brew install font-noto-sans-glagolitic
yes | brew install font-noto-sans-gothic
yes | brew install font-noto-sans-grantha
yes | brew install font-noto-sans-gujarati
yes | brew install font-noto-sans-gujarati-ui
yes | brew install font-noto-sans-gunjala-gondi
yes | brew install font-noto-sans-gurmukhi
yes | brew install font-noto-sans-gurmukhi-ui
yes | brew install font-noto-sans-hanifi-rohingya
yes | brew install font-noto-sans-hanunoo
yes | brew install font-noto-sans-hatran
yes | brew install font-noto-sans-hebrew
yes | brew install font-noto-sans-hk
yes | brew install font-noto-sans-imperial-aramaic
yes | brew install font-noto-sans-indic-siyaq-numbers
yes | brew install font-noto-sans-inscriptional-pahlavi
yes | brew install font-noto-sans-inscriptional-parthian
yes | brew install font-noto-sans-javanese
yes | brew install font-noto-sans-jp
yes | brew install font-noto-sans-kaithi
yes | brew install font-noto-sans-kannada
yes | brew install font-noto-sans-kannada-ui
yes | brew install font-noto-sans-kawi
yes | brew install font-noto-sans-kayah-li
yes | brew install font-noto-sans-kharoshthi
yes | brew install font-noto-sans-khmer
yes | brew install font-noto-sans-khmer-ui
yes | brew install font-noto-sans-khojki
yes | brew install font-noto-sans-khudawadi
yes | brew install font-noto-sans-kr
yes | brew install font-noto-sans-lao
yes | brew install font-noto-sans-lao-looped
yes | brew install font-noto-sans-lao-ui
yes | brew install font-noto-sans-lepcha
yes | brew install font-noto-sans-limbu
yes | brew install font-noto-sans-linear-a
yes | brew install font-noto-sans-linear-b
yes | brew install font-noto-sans-lisu
yes | brew install font-noto-sans-lycian
yes | brew install font-noto-sans-lydian
yes | brew install font-noto-sans-mahajani
yes | brew install font-noto-sans-malayalam
yes | brew install font-noto-sans-malayalam-ui
yes | brew install font-noto-sans-mandaic
yes | brew install font-noto-sans-manichaean
yes | brew install font-noto-sans-marchen
yes | brew install font-noto-sans-masaram-gondi
yes | brew install font-noto-sans-math
yes | brew install font-noto-sans-mayan-numerals
yes | brew install font-noto-sans-medefaidrin
yes | brew install font-noto-sans-meetei-mayek
yes | brew install font-noto-sans-mende-kikakui
yes | brew install font-noto-sans-meroitic
yes | brew install font-noto-sans-miao
yes | brew install font-noto-sans-modi
yes | brew install font-noto-sans-mongolian
yes | brew install font-noto-sans-mono
yes | brew install font-noto-sans-mono-cjk-hk
yes | brew install font-noto-sans-mono-cjk-jp
yes | brew install font-noto-sans-mono-cjk-kr
yes | brew install font-noto-sans-mono-cjk-sc
yes | brew install font-noto-sans-mono-cjk-tc
yes | brew install font-noto-sans-mro
yes | brew install font-noto-sans-multani
yes | brew install font-noto-sans-myanmar
yes | brew install font-noto-sans-myanmar-ui
yes | brew install font-noto-sans-n-ko
yes | brew install font-noto-sans-nabataean
yes | brew install font-noto-sans-nag-mundari
yes | brew install font-noto-sans-nandinagari
yes | brew install font-noto-sans-new-tai-lue
yes | brew install font-noto-sans-newa
yes | brew install font-noto-sans-nko
yes | brew install font-noto-sans-nko-unjoined
yes | brew install font-noto-sans-nushu
yes | brew install font-noto-sans-ogham
yes | brew install font-noto-sans-ol-chiki
yes | brew install font-noto-sans-old-hungarian
yes | brew install font-noto-sans-old-italic
yes | brew install font-noto-sans-old-north-arabian
yes | brew install font-noto-sans-old-permic
yes | brew install font-noto-sans-old-persian
yes | brew install font-noto-sans-old-sogdian
yes | brew install font-noto-sans-old-south-arabian
yes | brew install font-noto-sans-old-turkic
yes | brew install font-noto-sans-oriya
yes | brew install font-noto-sans-oriya-ui
yes | brew install font-noto-sans-osage
yes | brew install font-noto-sans-osmanya
yes | brew install font-noto-sans-pahawh-hmong
yes | brew install font-noto-sans-palmyrene
yes | brew install font-noto-sans-pau-cin-hau
yes | brew install font-noto-sans-phags-pa
yes | brew install font-noto-sans-phagspa
yes | brew install font-noto-sans-phoenician
yes | brew install font-noto-sans-psalter-pahlavi
yes | brew install font-noto-sans-rejang
yes | brew install font-noto-sans-runic
yes | brew install font-noto-sans-samaritan
yes | brew install font-noto-sans-saurashtra
yes | brew install font-noto-sans-sc
yes | brew install font-noto-sans-sharada
yes | brew install font-noto-sans-shavian
yes | brew install font-noto-sans-siddham
yes | brew install font-noto-sans-signwriting
yes | brew install font-noto-sans-sinhala
yes | brew install font-noto-sans-sinhala-ui
yes | brew install font-noto-sans-sogdian
yes | brew install font-noto-sans-sora-sompeng
yes | brew install font-noto-sans-soyombo
yes | brew install font-noto-sans-sundanese
yes | brew install font-noto-sans-sunuwar
yes | brew install font-noto-sans-syloti-nagri
yes | brew install font-noto-sans-symbols
yes | brew install font-noto-sans-symbols-2
yes | brew install font-noto-sans-syriac
yes | brew install font-noto-sans-syriac-eastern
yes | brew install font-noto-sans-syriac-estrangela
yes | brew install font-noto-sans-syriac-western
yes | brew install font-noto-sans-tagalog
yes | brew install font-noto-sans-tagbanwa
yes | brew install font-noto-sans-tai-le
yes | brew install font-noto-sans-tai-tham
yes | brew install font-noto-sans-tai-viet
yes | brew install font-noto-sans-takri
yes | brew install font-noto-sans-tamil
yes | brew install font-noto-sans-tamil-supplement
yes | brew install font-noto-sans-tamil-ui
yes | brew install font-noto-sans-tangsa
yes | brew install font-noto-sans-tc
yes | brew install font-noto-sans-telugu
yes | brew install font-noto-sans-telugu-ui
yes | brew install font-noto-sans-thaana
yes | brew install font-noto-sans-thai
yes | brew install font-noto-sans-thai-looped
yes | brew install font-noto-sans-thai-ui
yes | brew install font-noto-sans-tibetan
yes | brew install font-noto-sans-tifinagh
yes | brew install font-noto-sans-tirhuta
yes | brew install font-noto-sans-ugaritic
yes | brew install font-noto-sans-vai
yes | brew install font-noto-sans-vithkuqi
yes | brew install font-noto-sans-wancho
yes | brew install font-noto-sans-warang-citi
yes | brew install font-noto-sans-yi
yes | brew install font-noto-sans-zanabazar-square
yes | brew install font-noto-serif
yes | brew install font-noto-serif-ahom
yes | brew install font-noto-serif-armenian
yes | brew install font-noto-serif-balinese
yes | brew install font-noto-serif-bengali
yes | brew install font-noto-serif-cjk
yes | brew install font-noto-serif-cjk-hk
yes | brew install font-noto-serif-cjk-jp
yes | brew install font-noto-serif-cjk-kr
yes | brew install font-noto-serif-cjk-sc
yes | brew install font-noto-serif-cjk-tc
yes | brew install font-noto-serif-devanagari
yes | brew install font-noto-serif-display
yes | brew install font-noto-serif-dives-akuru
yes | brew install font-noto-serif-dogra
yes | brew install font-noto-serif-ethiopic
yes | brew install font-noto-serif-georgian
yes | brew install font-noto-serif-grantha
yes | brew install font-noto-serif-gujarati
yes | brew install font-noto-serif-gurmukhi
yes | brew install font-noto-serif-hebrew
yes | brew install font-noto-serif-hentaigana
yes | brew install font-noto-serif-hk
yes | brew install font-noto-serif-jp
yes | brew install font-noto-serif-kannada
yes | brew install font-noto-serif-khitan-small-script
yes | brew install font-noto-serif-khmer
yes | brew install font-noto-serif-khojki
yes | brew install font-noto-serif-kr
yes | brew install font-noto-serif-lao
yes | brew install font-noto-serif-makasar
yes | brew install font-noto-serif-malayalam
yes | brew install font-noto-serif-myanmar
yes | brew install font-noto-serif-np-hmong
yes | brew install font-noto-serif-nyiakeng-puachue-hmong
yes | brew install font-noto-serif-old-uyghur
yes | brew install font-noto-serif-oriya
yes | brew install font-noto-serif-ottoman-siyaq
yes | brew install font-noto-serif-sc
yes | brew install font-noto-serif-sinhala
yes | brew install font-noto-serif-tamil
yes | brew install font-noto-serif-tangut
yes | brew install font-noto-serif-tc
yes | brew install font-noto-serif-telugu
yes | brew install font-noto-serif-thai
yes | brew install font-noto-serif-tibetan
yes | brew install font-noto-serif-todhri
yes | brew install font-noto-serif-toto
yes | brew install font-noto-serif-vithkuqi
yes | brew install font-noto-serif-yezidi
yes | brew install font-noto-traditional-nushu
yes | brew install font-noto-znamenny-musical-notation
